export const GET_UNIT_DETAILS_PENDING = "GET_UNIT_DETAILS_PENDING";
export const GET_UNIT_DETAILS_SUCCESS = "GET_UNIT_DETAILS_SUCCESS";
export const GET_UNIT_DETAILS_ERROR = "GET_UNIT_DETAILS_ERROR";
export const GET_UNIT_DETAILS_SAGA = "GET_UNIT_DETAILS_SAGA";
