export const GET_UNITS_PENDING = "GET_UNITS_PENDING";
export const GET_UNITS_SUCCESS = "GET_UNITS_SUCCESS";
export const GET_UNITS_ERROR = "GET_UNITS_ERROR";
export const GET_UNITS_SAGA = "GET_UNITS_SAGA";
